<h3>배열 데이터를 효과적으로 다루는 NumPy</h3>

In [1]:
import numpy as np

<h4>배열 생성하기</h4>

In [4]:
data1 = [0,1,2,3,4,5]
a1 = np.array(data1) # nd(n-dimension)array
a1

array([0, 1, 2, 3, 4, 5])

In [5]:
data2 = [0.1,5,4,12,0.5]
a2 = np.array(data2)
a2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [6]:
a1.dtype

dtype('int32')

In [7]:
a2.dtype

dtype('float64')

In [8]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
b1 = np.arange(12).reshape(4,3)
b1.shape

b1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.array(['1,5','0.62','2','3.14','3.141592'])

array(['1,5', '0.62', '2', '3.14', '3.141592'], dtype='<U8')

In [17]:
str_a1 = np.array(['1.567','0.123','5.123','9','8'])
num_a1 = str_a1.astype(float)
num_a1

array([1.567, 0.123, 5.123, 9.   , 8.   ])

In [18]:
num_f1 = np.array([10,21,0.549,4.75,5.98])
num_i1 = num_f1.astype(int)
num_i1

array([10, 21,  0,  4,  5])

In [19]:
num_f1.dtype

dtype('float64')

In [20]:
num_i1.dtype

dtype('int32')

<h4>배열의 연산</h4>

In [23]:
arr1 = np.array([10,20,30,40])
arr2 = np.array([1,2,3,4])

In [24]:
arr1 + arr2

array([11, 22, 33, 44])

In [25]:
arr1 - arr2

array([ 9, 18, 27, 36])

In [27]:
arr2 * 2

array([2, 4, 6, 8])

In [29]:
arr2 ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [30]:
arr1 * arr2

array([ 10,  40,  90, 160])

In [31]:
arr1 / arr2

array([10., 10., 10., 10.])

In [32]:
arr1 / (arr2 ** 2)

array([10.        ,  5.        ,  3.33333333,  2.5       ])

In [33]:
arr1 > 20

array([False, False,  True,  True])

In [35]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [36]:
[arr3.sum(), arr3.mean()]

[10, 2.0]

In [37]:
[arr3.std(), arr3.var()]

[1.4142135623730951, 2.0]

In [38]:
[arr3.min(), arr3.max()]

[0, 4]

In [40]:
arr4 = np.arange(1,5)
arr4

array([1, 2, 3, 4])

In [41]:
arr4.cumsum()

array([ 1,  3,  6, 10], dtype=int32)

In [42]:
arr4.cumprod()

array([ 1,  2,  6, 24], dtype=int32)

In [43]:
A = np.array([0,1,2,3]).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [44]:
B = np.array([3,2,0,1]).reshape(2,2)
B

array([[3, 2],
       [0, 1]])

In [45]:
# 행렬곱
A.dot(B)

array([[0, 1],
       [6, 7]])

In [46]:
np.dot(A,B)

array([[0, 1],
       [6, 7]])

In [47]:
# 전치행렬
np.transpose(A)

array([[0, 2],
       [1, 3]])

In [48]:
A.transpose()

array([[0, 2],
       [1, 3]])

In [49]:
# 역행렬
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [50]:
# 행렬 A의 행렬식
np.linalg.det(A)

-2.0

<h4>배열의 인덱싱과 슬라이싱</h4>

In [53]:
a1 = np.array([0,10,20,30,40,50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [59]:
a2 = np.arange(10,100,10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [63]:
a2[0,2]

30

In [64]:
a2[2,2] = 95
a2

array([[10, 20, 30],
       [45, 55, 65],
       [70, 80, 95]])

In [65]:
a2[1] = np.array([45,55,65])
a2

array([[10, 20, 30],
       [45, 55, 65],
       [70, 80, 95]])

In [66]:
a2[1] = [47,57,67]
a2

array([[10, 20, 30],
       [47, 57, 67],
       [70, 80, 95]])

In [67]:
a2[[0,2],[0,1]]

array([10, 80])

In [56]:
# 파이썬 리스트
test = [[0,10], [20,30], [40,50]]
test[0][1]

10

In [57]:
# ndarray일 때는 다음과 같은 방법이 가능하다
test = [[0,10], [20,30], [40,50]]
test2 = np.array(test)
test2[0,1]

10

In [68]:
a = np.array([1,2,3,4,5,6])
a[a>3]

array([4, 5, 6])

In [70]:
a>3

array([False, False, False,  True,  True,  True])

In [72]:
a[(a%2)==0]

array([2, 4, 6])

In [74]:
b1 = np.array([0,10,20,30,40,50])
b1[1:4]

array([10, 20, 30])

In [76]:
b1[2:5] = np.array([25,35,45])
b1

array([ 0, 10, 25, 35, 45, 50])

In [77]:
b1[3:6]=60
b1

array([ 0, 10, 25, 60, 60, 60])

In [78]:
b2 = np.arange(10,100,10).reshape(3,3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [79]:
b2[1:3, 1:3]

array([[50, 60],
       [80, 90]])

In [80]:
b2[:3, 1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [81]:
b2[1][0:2]

array([40, 50])

In [83]:
b2[0:2, 1:3] = np.array([[25,35], [55,65]])
b2

array([[10, 25, 35],
       [40, 55, 65],
       [70, 80, 90]])