In [1]:
import tensorflow as tf

c:\users\student\anaconda3\envs\py360\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\users\student\anaconda3\envs\py360\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\users\student\anaconda3\envs\py360\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\users\student\anaconda3\envs\py360\lib\site-packages\tensorflow\

In [2]:
tf.__version__

'1.6.0'

In [8]:
node1 = tf.constant(3.0, dtype=tf.float32)
node2 = tf.constant(4.0, dtype=tf.float32)

In [9]:
print(node1, node2)

Tensor("Const_1:0", shape=(), dtype=float32) Tensor("Const_2:0", shape=(), dtype=float32)


In [10]:
sess = tf.Session()

In [11]:
sess.run([node1, node2])

[3.0, 4.0]

In [13]:
node3 = tf.add(node1, node2)
node3

<tf.Tensor 'Add_1:0' shape=() dtype=float32>

In [14]:
sess.run(node3)

7.0

In [16]:
sess.run([node3, node1, node2])

[7.0, 3.0, 4.0]

In [17]:
sess.close()

In [19]:
input_data = [1,2,3,4,5]
x = tf.placeholder(dtype=tf.float32)
y = x * 2

sess = tf.Session()
result = sess.run(y, feed_dict={x: input_data})

print(result)

[ 2.  4.  6.  8. 10.]


In [22]:
input_data = [1,2,3,4,5]
x = tf.placeholder(dtype=tf.float32)
W = tf.Variable([2], dtype=tf.float32)
y = W * x
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
result = sess.run(y, feed_dict={x: input_data})
print(result)

[ 2.  4.  6.  8. 10.]


In [31]:
# 과제 1: Tensorflow를 이용한 그래프 생성 및 실행하는 코드 작성
a = tf.constant(5.0, dtype=tf.float32)
b = tf.constant(2.0, dtype=tf.float32)
c = tf.constant(3.0, dtype=tf.float32)
sess = tf.Session()
d = tf.multiply(a,b)
# d = sess.run(d)
# print(d)
e = tf.add(b,c)
# e = sess.run(e)
# print(e)
f = tf.subtract(d,e)
f = sess.run(f)
print(f)
sess.close()

5.0


In [34]:
# 텐서플로우에서 행렬의 표현
x = tf.constant([ [1.0, 2.0, 3.0] ]) # 1행 3열
w = tf.constant([ [2.0],[2.0],[2.0] ]) # 3행 1열
y = tf.matmul(x,w)
print(x.get_shape())
print(w.get_shape())

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
result = sess.run(y)

print(result)

(1, 3)
(3, 1)
[[12.]]


In [36]:
# Constant 및 Variable 뿐 아니라, PlaceHolder에도 행렬로 저장 가능
input_data = [ [1.,2.,3.], [1.,2.,3.], [2.,3.,4.] ] # 3행 3열
x = tf.placeholder(dtype=tf.float32, shape=[None,3])
w = tf.Variable([ [2.], [2.], [2.] ], dtype=tf.float32) # 3행 1열
y = tf.matmul(x, w)

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
result = sess.run(y, feed_dict={x: input_data})

print(result)

[[12.]
 [12.]
 [18.]]
